joint_0:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_0
    joint_speed: 1.5
    motor:
        id: 7
        init: 512
        min: 0
        max: 1023

joint_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_1
    joint_speed: 1.5
    motor:
        id: 8
        init: 512
        min: 0
        max: 1023
