joint_0:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sensor_head_yaw_joint
    joint_speed: 1.5
    motor:
        id: 10
        init: 512
        min: 0
        max: 1023

joint_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sensor_head_pitch_joint
    joint_speed: 1.5
    motor:
        id: 12
        init: 512
        min: 0
        max: 1023
