sensor_head_yaw_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sensor_head_yaw_joint
    joint_speed: 1.5
    motor:
        id: 1
        init: 512
        min: 340
        max: 800

sensor_head_pitch_joint:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: sensor_head_pitch_joint
    joint_speed: 1.5
    motor:
        id: 2
        init: 700
        min: 500
        max: 900
