sensor_head_yaw_joint_position_controller:
  type: "position_controllers/JointPositionController"
  joint: sensor_head_yaw_joint
  
sensor_head_pitch_joint_position_controller:
  type: "position_controllers/JointPositionController"
  joint: sensor_head_pitch_joint  